"""Add Statistic

Revision ID: 86c9339c5ffd
Revises: c02d6e774dc7
Create Date: 2025-05-28 23:21:02.124048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c9339c5ffd'
down_revision: Union[str, None] = 'c02d6e774dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Додаємо нову колонку
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        # Змінюємо існуючу колонку (встановлюємо NOT NULL)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_nullable=True) # Важливо вказати, що раніше було True
        # Створюємо індекси
        batch_op.create_index('ix_tasks_completed', ['completed'], unique=False)
        batch_op.create_index('ix_tasks_completed_at', ['completed_at'], unique=False)
        # Видаляємо стару колонку
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Важливо також оновити downgrade, якщо ви плануєте відкочуватись
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index('ix_tasks_completed_at')
        batch_op.drop_index('ix_tasks_completed')
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_nullable=False)
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
