"""Add Remind_Up

Revision ID: 8e87404e174f
Revises: bf24dc39e2e0
Create Date: 2025-05-27 13:26:07.133207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e87404e174f'
down_revision: Union[str, None] = 'bf24dc39e2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('follow_up_time', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'followe_up_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('followe_up_time', sa.INTEGER(), nullable=True))
    op.drop_column('tasks', 'follow_up_time')
    # ### end Alembic commands ###
