"""Add Remind_Up

Revision ID: bf24dc39e2e0
Revises: c8041e9a3ba6
Create Date: 2025-05-27 13:01:00.952339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf24dc39e2e0'
down_revision: Union[str, None] = 'c8041e9a3ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('follow_up_sent', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('followe_up_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'followe_up_time')
    op.drop_column('tasks', 'follow_up_sent')
    op.drop_column('tasks', 'reminder_sent')
    # ### end Alembic commands ###
