"""Add Remind

Revision ID: d165fb06474b
Revises: d17986cfcb7f
Create Date: 2025-05-25 16:05:23.627811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd165fb06474b'
down_revision: Union[str, None] = 'd17986cfcb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('remind_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('is_reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_reminded')
    op.drop_column('tasks', 'remind_at')
    # ### end Alembic commands ###
